include: package:pedantic/analysis_options.yaml

linter:
  rules:
    camel_case_types: true
    directives_ordering: true
    omit_local_variable_types: false
    prefer_single_quotes: false

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  exclude:
    # ignore generated files and tests
    - "**/*.g.dart"
    - "**/*_test.dart"
    - "example/**/*"
