name: bloom_share_kit
description: Easily allow your users to share their verified personal information directly with your application.
version: 1.0.0
authors:
  - Bloom Team <team@bloom.co>
  - Peter Chung <touhonoob@gmail.com>
homepage: https://github.com/hellobloom/share-kit-flutter

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ^1.5.0

dependencies:
  flutter:
    sdk: flutter
  ethereum_util: ^1.2.0
  merkletree: ^1.0.3
  meta: ^1.1.6
  sortedmap: ^0.4.2
  collection: ^1.14.11
  buffer: ^1.0.6
  json_annotation: ^3.1.1
  json_serializable: ^3.5.1
  flutter_svg: ^0.18.1
  url_launcher: ^5.7.10
  qr: ^1.1.1
  convert: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.7
  test: ^1.15.7
  mockito: ^4.0.0
  storyboard: ^0.0.4
  pedantic: ^1.9.2

flutter:
